/*
 * This source file was generated by the Gradle 'init' task
 */

package ballPi;

import org.junit.Test;

public class MainTest {

  @Test
  public boolean appHasAGreeting() {
    return true;

  }
}
