
/*
 * This source file was generated by the Gradle 'init' task
 *
 */

package ballPi;
import ballPi.view.MainView;


public class Main {
  public static void main(String[] args) {
    new MainView(1280,720);
  }
}



//import no.uib.inf101.sshmanager.view.MainFrame;
//
//public class sshmanager {
	//public static void main(String[] args) {
//
		//@SuppressWarnings("unused")
		//MainFrame mainFrame = new MainFrame(1280, 720);
//
	//}
	//
//}

